import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { GlobalStyle } from './page.styled'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Alhodhod',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <GlobalStyle/>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
